<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>CA1725,CA1716,CS1591,CA1715</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <Product>SPhysics</Product>
    <Title>SPhysics</Title>
    <Version>0.2.0</Version>
    <Description>Physics library based on .NET generic math.</Description>
    <PackageTags>physics; generic-physics; mechanics; gravitation; csharp</PackageTags>
    <PackageProjectUrl>https://github.com/jirikostiha/sphysics</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)..\..\ijkdata.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\readme.md" Link="readme.md" Pack="true" PackagePath="readme.md" />
    <None Update="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SMath" />
  </ItemGroup>

</Project>
